'use client';

import { useCallback } from 'react';
import Link from 'next/link';
import { Card, SectionHead, Chip, TableSkeleton, EmptyState, ErrorState, Meter, CAMPAIGN_TONE, humanStatus } from '@/components/ui/kit';
import { Icon } from '@/components/ui/icons';
import { useApi, useLiveRefresh, inr, pct, dateTime } from '@/components/ui/data';

/**
 * Campaigns are TooEz's marketing surface: every one was generated by the
 * Offer Agent, cleared by the Risk Agent, and approved by the merchant.
 */
export default function CampaignsPage() {
  const { data, loading, error, reload } = useApi<any>('/api/dashboard/campaigns');
  useLiveRefresh(useCallback(() => reload(true), [reload]));
  const rows = data?.rows ?? [];

  const live = rows.filter((c: any) => c.status === 'LIVE');
  const pending = rows.filter((c: any) => c.status === 'PENDING_APPROVAL');
  const revenue = rows.reduce((s: number, c: any) => s + c.revenue_paise, 0);
  const subsidy = rows.reduce((s: number, c: any) => s + c.discount_cost_paise, 0);

  return (
    <div className="fade-up space-y-4">
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="text-[21px] font-semibold tracking-[-0.02em] text-ink">Campaigns</h1>
          <p className="mt-1 text-[12.5px] text-ink-3">
            Time-boxed offers the revenue agents created against inventory that was about to go unsold.
          </p>
        </div>
        <Link className="btn-primary" href="/dashboard/agents"><Icon.Plus /> New campaign</Link>
      </div>

      {rows.length > 0 && (
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
          <Mini label="Live now" value={String(live.length)} tone="good" />
          <Mini label="Awaiting approval" value={String(pending.length)} tone={pending.length ? 'warn' : 'neutral'} />
          <Mini label="Campaign revenue" value={inr(revenue)} tone="brand" />
          <Mini label="Discount given" value={inr(subsidy)} tone="sand" />
        </div>
      )}

      {error ? <Card><ErrorState message={error} onRetry={() => reload()} /></Card>
        : loading && !data ? <Card><TableSkeleton cols={6} /></Card>
        : !rows.length ? (
          <Card><EmptyState title="No campaigns yet" icon={<Icon.Campaigns size={26} />}
            hint="Run the revenue agents to find an opportunity and draft your first offer."
            action={<Link className="btn-primary" href="/dashboard/agents">Run revenue agents</Link>} /></Card>
        ) : (
          <div className="grid gap-3 lg:grid-cols-2">
            {rows.map((c: any) => (
              <Card key={c.id} className="card-pad">
                <div className="flex items-start justify-between gap-3">
                  <div className="min-w-0">
                    <div className="flex flex-wrap items-center gap-2">
                      <Chip tone={CAMPAIGN_TONE[c.status] ?? 'neutral'}>{humanStatus(c.status)}</Chip>
                      <span className="text-[16px] font-semibold tnum text-ink">{inr(c.price_paise)}</span>
                      <span className="text-[12px] tnum text-ink-4 line-through">{inr(c.list_price_paise)}</span>
                      <Chip tone="neutral">{pct(c.discount_pct)} off</Chip>
                    </div>
                    <div className="mt-1.5 truncate text-[13px] font-medium text-ink">{c.product_name}</div>
                  </div>
                  {(c.status === 'LIVE' || c.status === 'COMPLETED') && (
                    <Link href={`/shop/${c.id}`} target="_blank" className="btn-ghost !py-1.5 !text-[11.5px] shrink-0">
                      <Icon.External /> Storefront
                    </Link>
                  )}
                </div>

                <p className="mt-2.5 line-clamp-2 text-[11.5px] leading-relaxed text-ink-3">{c.reasoning}</p>

                <div className="mt-3 border-t border-line pt-3">
                  <div className="mb-1 flex justify-between text-[11.5px]">
                    <span className="text-ink-3">Units sold</span>
                    <span className="tnum text-ink">{c.units_sold} of {c.units_offered}</span>
                  </div>
                  <Meter value={c.units_sold} max={c.units_offered} tone={c.status === 'LIVE' ? 'good' : 'brand'} />
                </div>

                <div className="mt-3 grid grid-cols-4 gap-2 text-center">
                  <Stat k="Revenue" v={inr(c.revenue_paise)} tone="text-good" />
                  <Stat k="Subsidy" v={inr(c.discount_cost_paise)} tone="text-sand" />
                  <Stat k="Margin" v={pct(c.margin_pct, 0)} />
                  <Stat k="Orders" v={String(c.order_count)} />
                </div>

                <div className="mt-3 flex items-center justify-between text-[10.5px] text-ink-4">
                  <span>created {dateTime(c.created_at)}</span>
                  <span>expires {dateTime(c.expires_at)}</span>
                </div>
              </Card>
            ))}
          </div>
        )}
    </div>
  );
}

function Mini({ label, value, tone }: { label: string; value: string; tone: string }) {
  const c = { good: 'text-good', warn: 'text-warn', brand: 'text-brand', sand: 'text-sand', neutral: 'text-ink' }[tone] ?? 'text-ink';
  return (
    <Card glass className="p-4">
      <div className="label">{label}</div>
      <div className={`mt-2 text-[22px] font-semibold leading-none tnum ${c}`}>{value}</div>
    </Card>
  );
}

function Stat({ k, v, tone = 'text-ink' }: { k: string; v: string; tone?: string }) {
  return (
    <div className="rounded-lg bg-surface-2 py-1.5">
      <div className={`text-[12.5px] font-medium tnum ${tone}`}>{v}</div>
      <div className="text-[9.5px] uppercase tracking-wider text-ink-4">{k}</div>
    </div>
  );
}
